#!/usr/bin/env ruby
require "airplay"
require "redis"
require_relative "../config/initializers/redis"

class AirPlayAgent
  def initialize(device_name)
    @player = Airplay[device_name].player
  end

  def start_playing
    while true
      begin
        key_for_next_song = Redis.current.lpop("playlist")
        sleep 1 and next unless key_for_next_song

        song_data = eval(Redis.current.get(key_for_next_song))
      rescue Redis::CannotConnectError => e
        puts "Redis connection error"
        wait 10 and next
      end

      @player.playlist << song_data[:url]
      @player.play
      wait

      Redis.current.del(key_for_next_song) rescue Redis::CannotConnectError
      begin
        File::delete(song_data[:path])
      rescue => e
        p e
      end
    end
  end

  private
  def wait
    sleep 1 while wait_for_playback?
    @player.cleanup
  end

  def wait_for_playback?
    return true if @player.playlist.next?
    @player.loading? || @player.playing?
  end
end

apple_tv = AirPlayAgent.new("Apple TV")
apple_tv.start_playing
